#!/bin/sh
export LD_LIBRARY_PATH="/media/feynman/3TBBackup/Scripts/CellSeeker/qtlib:/media/feynman/3TBBackup/Scripts/CellSeeker/lib:$LD_LIBRARY_PATH"

"/media/feynman/3TBBackup/Scripts/CellSeeker/realbin/newstack" "$@"
